version: '3.8'

services:
  lafayette-bot:
    image: discord-bot-lafayette:latest # Replace with your actual image name
    container_name: lafayette-bot
    restart: unless-stopped
    environment:
      # Environment variables for the bot - use your own values or set them in a .env file
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - BOT_OWNER_ID=${GUILD_ID}
      - DP_FFMPEG_PATH=/usr/bin/ffmpeg
    volumes:
      - ./bot_data:/usr/src/app/data  # persistent storage for bot data - make sure to set proper permissions
    
    # Resource limits (optional)
    #deploy:
    #  resources:
    #    limits:
    #      memory: 512M
    #      cpus: '0.5'
    #    reservations:
    #      memory: 256M
    #      cpus: '0.25'