version: '3.8'

services:
  lafayette-bot:
    image: ghcr.io/vojtechmarek-dev/discord-bot-lafayette:main
    container_name: lafayette-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      # Add any other environment variables your bot needs
      # - SOME_API_KEY=${SOME_API_KEY}
      # - DATABASE_URL=${DATABASE_URL}
    # Uncomment if your bot needs persistent storage
    # volumes:
    #   - ./data:/app/data
    #   - ./logs:/app/logs
    
    # Uncomment if your bot exposes any ports (like a web dashboard)
    # ports:
    #   - "3000:3000"
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Health check (optional, adjust the command based on your bot)
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

networks:
  default:
    name: lafayette-bot-network